#! /bin/sh
### BEGIN INIT INFO
# Provides: Google-Assistant
# Required-Start: $remote_fs $syslog $network
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Google-Assistant
# Description: This file starts the Google Assitant Service
#
### END INIT INFO

SCRIPT_DIR=/home/kaiyoti/scripts/

case "$1" in
 start)
   $SCRIPT_DIR/ga-start.sh
   ;;
 stop)
   $SCRIPT_DIR/ga-stop.sh
   sleep 10
   ;;
 restart)
   $SCRIPT_DIR/ga-stop.sh
   sleep 20
   #start-stop-daemon --start --quiet -u kaiyoti --exec $SCRIPT_DIR/ga-start.sh
   $SCRIPT_DIR/ga-start.sh
   ;;
 *)
   echo "Usage: google-assistant {start|stop|restart}" >&2
   exit 3
   ;;
esac

